# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ope's blog
email: owner@opemipo.dev
description: > # this means to ignore newlines until "baseurl:"
  Weblog mostly about my software engineering adventures and thoughts

url: "https://blog.opemipo.dev" # the base hostname & protocol for your site
twitter_username: opeispo
github_username:  opethe1st
permalink: /posts/:year/:month/:day/:title:output_ext

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
# google_analytics:
disqus_shortname: blog-opemipo-dev
plugins:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-seo-tag
    - jekyll-redirect-from

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
